spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flush_card
    username: ${SQL_USER}
    password: ${SQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: utf-8
